os: linux
language: generic

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  global:
  - VERSION_LATEST: 5.7.1

jobs:
  include:
    - env: VERSION=5.7.1
    - env: VERSION=5.7
    - env: VERSION=5.6.2
    # - env: VERSION=5.6.1
    # - env: VERSION=5.6
    - env: VERSION=5.5.1
    - env: VERSION=5.5
    # - env: VERSION=5.4.2
    - env: VERSION=5.4.1
    # - env: VERSION=5.4
    - env: VERSION=5.3.1
    # - env: VERSION=5.3
    - env: VERSION=5.2
    - env: VERSION=5.1.1
    - env: VERSION=5.1
    # - env: VERSION=5.0.8
    # - env: VERSION=5.0.7
    # - env: VERSION=5.0.6
    # - env: VERSION=5.0.5
    # - env: VERSION=5.0.4
    # - env: VERSION=5.0.3
    # - env: VERSION=5.0.2
    # - env: VERSION=5.0.1
    # - env: VERSION=5.0.0
    # - env: VERSION=4.3.17

script:
  - make build

deploy:
  provider: script
  script: make deploy
  on:
    branch: master
